
---
- name: 1 create nginx includes dir
  file:
    state: directory
    path: /etc/nginx/includes/
    mode: og+wr
    owner: root
    group: root

- name: 2 NGINX includes config
  template:
    src: nginx_ts.j2
    dest: '/etc/nginx/{{ nginx_ts_conf }}'
    mode: og+wr
    owner: root
    group: root

- name: 3 remove comments from NGINX site default
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: '#\s*?.*$'
    state: absent

- name: 4 remove location / from NGINX site default
  lineinfile:
    path: /etc/nginx/sites-available/default
    regexp: 'location\s/(.|\n)+?\}'
    state: absent

- name: 5 insert ts conf to NGINX site default
  lineinfile:
    path: /etc/nginx/sites-available/default
    insertafter: 'server_name _;'
    line: '        include {{ nginx_ts_conf }};'
    mode: og+wr
    owner: root
    group: root

- name: 6 enable NGINX default config
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
  notify: reload_webserver

- name: 7 reload NGINX
  command: systemctl reload nginx


