---
- name: 1 Install aptitude
  package:
    name: aptitude
    state: present

- name: 2 Update and upgrade apt packages
  apt:
    upgrade: 'True'
    update_cache: 'True'
    cache_valid_time: 86400 #One day

- name: 3 Install apt packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - python3-pip
    - python3-setuptools
    - wget
    - git
    - vim
    - nginx
    - apt-transport-https
    - curl
    - tmux
    - lynx

- name: 4 pip3 executable
  command: which pip3
  register: pip3_path

- name: 5.1 get nodejs 
  get_url:
    url: https://nodejs.org/dist/v14.17.5/node-v14.17.5-linux-x64.tar.xz
    dest: /root

- name: 5.2 unpack nodejs
  unarchive:
    remote_src: yes
    src: /root/node-v14.17.5-linux-x64.tar.xz
    dest: /root/

- name: 5.3 cp node binary to /usr/local/bin
  copy:
    src: /root/node-v14.17.5-linux-x64/bin/node
    dest: /usr/local/bin/node
    mode: a+x
    remote_src: yes

- name: 6.1 download npm installer
  get_url:
      url: https://www.npmjs.com/install.sh
      dest: /root

- name: 6.2 run npm installer
  command: 
    cmd: "sh /root/install.sh"
 
- name: 6.3 /usr/local/lib/node_modules/npm as npm default
  command:
    cmd: update-alternatives --install /usr/bin/npm npm /usr/local/lib/node_modules/npm/bin/npm-cli.js 0

- name: 6.4 install PM2
  command:
    cmd: npm install pm2 -g