- hosts: all
  become: yes
  roles:
    - role: utils
      tags:
        - utils
        - all
    - role: ts
      tags:
        - ts
        - all
    - role: webserver
      tags:
        - webserver
        - all
